export const projects = [
    {
        id: 1,
        category: "frontend",
        title: "Bhinneka Dev – Developer Portfolio Website",
        image: "/assets/work/thum1.jpeg",
        link: "",
        github: "",
        tech: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    },
    {
        id: 2,
        category: "fullstack",
        title: "BMKG Bengkulu Guest Book",
        image: "/assets/work/thum2.png",
        link: "",
        github: "",
        tech: [
            "React",
            "Next.js",
            "Node.js",
            "Nest.js",
            "Supabase",
            "TypeScript",
            "Tailwind CSS",
        ],
    },
    {
        id: 3,
        category: "fullstack",
        title: "Local Geophysics Database of Bengkulu",
        image: "/assets/work/thum3.png",
        link: "",
        github: "",
        tech: [
            "React",
            "Next.js",
            "Nest.js",
            "Node.js",
            "Supabase",
            "TypeScript",
            "Tailwind CSS",
        ],
    },
    {
        id: 4,
        category: "frontend",
        title: "Met Flight Radar – Meteorological Radar Integration System",
        image: "/assets/work/thum4.png",
        link: "",
        github: "",
        tech: ["React", "Next.js", "Rest API", "TypeScript", "Tailwind CSS"],
    },
    {
        id: 5,
        category: "fullstack",
        title: "PTSP – Online Service Management System",
        image: "/assets/work/thum5.png",
        link: "",
        github: "",
        tech: [
            "React",
            "Next.js",
            "Nest.js",
            "Node.js",
            "Firebase",
            "JavaScript",
            "Tailwind CSS",
        ],
    },
    {
        id: 6,
        category: "fullstack",
        title: "Online Climatology Organizational Structure",
        image: "/assets/work/thum6.png",
        link: "",
        github: "",
        tech: [
            "React",
            "Next.js",
            "Nest.js",
            "Node.js",
            "Supabase",
            "TypeScript",
            "Tailwind CSS",
        ],
    },
    {
        id: 7,
        category: "fullstack",
        title: "Academic Information System for UNJANI Faculty",
        image: "/assets/work/thum7.jpeg",
        link: "",
        github: "",
        tech: ["PHP", "MySQL", "Bootstrap"],
    },
];
